# Generated by Django 4.0.1 on 2022-02-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('profile_photo', models.ImageField(upload_to='photos')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_employee.department')),
            ],
        ),
    ]
